<section id="main-slider" class="no-margin">
    <div class="carousel slide wet-asphalt">
        <div class="carousel-inner">
            <div class="item active" style="background-image: url(<?php echo \Module\Foundation\Actions::path('www-theme') ?>/images/slider/bg1.jpg)">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="carousel-content center centered">
                                <h2 class="boxed animation animated-item-1">Experience Rapid Application Framework</h2>
                                <h4 class="animation animated-item-2">Poirot, The Service Oriented, EventDriven PHP Experimental Framewrok.</h4>
                                <br>
                                <a class="btn btn-lg animation animated-item-3" target="_blank" href="https://github.com/phPoirot">Github</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

