<header class="bg-primary text-white">
    <div class="container text-center">
        <h1>Experience Rapid Application Framework</h1>
        <p class="lead">Poirot, The Service Oriented, EventDriven PHP Experimental Framework.</p>
        <a class="btn btn-lg animation animated-item-3" target="_blank" href="https://github.com/phPoirot">Github</a>
    </div>
</header>

<section id="simplicity">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h2>Simplicity</h2>
                <p class="lead">Easy to adapt the framework to your needs. It is explicitly designed to work efficiently as API Server.</p>
            </div>
        </div>
    </div>
</section>

<section id="reusability" class="bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h2>Reusability</h2>
                <p class="lead">Building blocks that can be used piece by piece with other applications or frameworks.</p>
            </div>
        </div>
    </div>
</section>

<section id="enterprise">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <h2>Enterprise</h2>
                <p class="lead">Extensible, Engineered with performance tuning in mind and Very short learning curve.</p>
            </div>
        </div>
    </div>
</section>

