<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">
            &copy; <?php echo date('Y') ?> <a target="_blank" href="https://github.com/phPoirot/" title="">Poirot Framework</a>. under MIT Licence.
        </p>
    </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>

<!-- Custom JavaScript for this theme -->
<script src="<?php echo \Module\Foundation\Actions::path('www-theme') ?>/js/scrolling-nav.js"></script>
